### ISSUE TITLE
Deagg: set contribution scale based on data

### ISSUE THREAD

**Issue by pmpowers-usgs** [usgs/earthquake-hazard-tool#199] opened 2017-04-10 14:27 UTC
Set the contribution to hazard (vertical scale) based on the maximum bar height. A reference value that can be used is supplied in the 'summary' data of each 'component' returned [JSON: response.data.element(forEach).summary.element(name='Mode (largest r-m bin)']

**Comment by jmfee-usgs** [comment] 2017-04-25 15:23
duplicate of #166

**Closed by jmfee-usgs** 2017-04-25 15:23 UTC
Labels: duplicate, ready
